# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Only for public API.

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "transport_types",
    hdrs = ["transport_types.h"],
)

cc_library(
    name = "socket_util",
    hdrs = ["socket_util.h"],
    deps = [
        ":transport_types",
        "//tpu_sync/transport/peregrine/src/internal/base:types",
        "//tpu_sync/transport/peregrine/src/internal/socket:socket_util",
        "//tpu_sync/transport/peregrine/src/internal/socket:tcp_socket_util",
        "//tpu_sync/transport/peregrine/src/internal/util",
        "@com_google_absl//absl/base:core_headers",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/types:span",
    ],
)

cc_test(
    name = "socket_util_test",
    srcs = ["socket_util_test.cc"],
    shard_count = 8,
    deps = [
        ":socket_util",
        ":transport_types",
        "//tpu_sync/transport/peregrine/src/internal/base:endpoint",
        "//tpu_sync/transport/peregrine/src/internal/base:ipaddr",
        "//tpu_sync/transport/peregrine/src/internal/base:types",
        "//tpu_sync/transport/peregrine/src/internal/socket:socket_tcp",
        "//tpu_sync/transport/peregrine/src/internal/socket:socket_util",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_absl//absl/synchronization",
        "@com_google_absl//absl/types:span",
        "@com_google_googletest//:gtest_main",
    ],
)
