// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef THIRD_PARTY_TPU_RAIDEN_TPU_SYNC_TELEMETRY_SHM_SHM_COLLECTOR_H_
#define THIRD_PARTY_TPU_RAIDEN_TPU_SYNC_TELEMETRY_SHM_SHM_COLLECTOR_H_

#include <array>
#include <cstdint>
#include <string>

#include "absl/container/flat_hash_map.h"
#include "tpu_sync/telemetry/shm/shm_layout.h"

namespace tpu_raiden::telemetry {

// Aggregated sample statistics and non-cumulative bucket counts for a histogram
// metric stream, aggregated across all live worker shared-memory segments.
//
// Invariants:
// - `bucket_counts` stores raw, non-cumulative counts per bucket as scraped
//   from `ShmHistogramSlot` to avoid loss of precision during aggregation.
// - Indices `0` through `kNumHistogramBuckets - 1` correspond to the upper
//   bounds in `kDefaultHistogramBuckets`.
// - Index `kNumHistogramBuckets` represents the `+Inf` overflow bucket.
// - `sample_count` is guaranteed to equal the sum of all elements in
//   `bucket_counts`.
//
// Consumption:
// - Exporters (e.g., Prometheus) must compute running cumulative sums when
//   emitting standard cumulative histogram bucket formats.
struct HistogramData {
  uint64_t sample_count = 0;
  double sample_sum = 0.0;
  std::array<uint64_t, kNumHistogramBuckets + 1> bucket_counts{};
};

// Point-in-time snapshot of telemetry metrics collected and aggregated across
// all active worker shared-memory segments.
//
// Data Organization:
// - Two-level map structure: Metric Name -> Encoded Labels -> Value.
// - The inner label key is the canonical representation generated by
//   `EncodeLabels` (comma-separated `key=value` pairs sorted lexicographically
//   by key). Unlabeled metrics use the empty string (`""`) as their key.
//
// Invariants:
// - Aggregation is additive: for matching metric names and label sets across
//   workers, counters, gauges, and histogram buckets/counts/sums are summed.
// - Contains only metrics from valid, non-corrupted segments where shared-lock
//   acquisition and TOC validation succeeded.
//
// Thread Safety & Consumption:
// - Move-only/copyable value object returned by
//   `ShmCollector::CollectMetrics()`.
// - Not internally synchronized; callers own the returned instance.
// - Typically consumed by telemetry exporters (e.g., `PrometheusShmExporter`)
//   to generate scrape endpoints or metrics exposition text.
struct AggregatedMetrics {
  // Metric Name -> Encoded Labels -> Value
  absl::flat_hash_map<std::string, absl::flat_hash_map<std::string, uint64_t>>
      counters;
  absl::flat_hash_map<std::string, absl::flat_hash_map<std::string, double>>
      gauges;
  absl::flat_hash_map<std::string,
                      absl::flat_hash_map<std::string, HistogramData>>
      histograms;

  [[nodiscard]] bool empty() const {
    return counters.empty() && gauges.empty() && histograms.empty();
  }
};

// Configuration options for the shared-memory telemetry collector.
struct ShmCollectorOptions {
  // Directory where shared-memory segment files (.mmap) are stored (e.g.
  // "/dev/shm" or "/tmp").
  std::string shm_dir;
};

// Thread-safe shared-memory telemetry collector.
// Scans for memory-mapped segment files in /dev/shm created by active TPU
// workers, acquires shared reader locks, aggregates counters, gauges, and
// histograms across worker processes, and cleans up dead worker files.
//
// Thread-safety note: `ShmCollector` instances are thread-safe and const
// member methods may be called concurrently from multiple threads.
class ShmCollector {
 public:
  explicit ShmCollector(ShmCollectorOptions options);

  // Scans the configured shared-memory directory, aggregates metric totals
  // across all live worker processes, and reaps dead worker files.
  //
  // Dead worker processes (whose exclusive lock can be acquired) are reaped
  // by unlinking their segment files. Dead worker metrics are intentionally
  // discarded upon reaping; only metrics from live processes are aggregated.
  // Downstream consumers should note that cumulative counters from reaped
  // workers are not retained.
  //
  // Gauges are aggregated across workers by addition. For non-additive gauges
  // (e.g. utilization or fraction), callers should supply rank-distinguishing
  // labels to avoid cross-worker aggregation.
  //
  // Histogram slots are read using relaxed atomic operations. Active writer
  // updates during scraping are eventually consistent.
  //
  // Thread safety: Concurrent invocations from multiple threads are safe.
  [[nodiscard]] AggregatedMetrics CollectMetrics() const;

 private:
  ShmCollectorOptions options_;
};

}  // namespace tpu_raiden::telemetry

#endif  // THIRD_PARTY_TPU_RAIDEN_TPU_SYNC_TELEMETRY_SHM_SHM_COLLECTOR_H_
