namespace tpu_raiden.transport.lib.flatbuf;

enum Constant:uint16 {
  MAGIC = 0x4452,  // 'RD' in little endian.
}

// v1 header layout for backwards compatibility (ver = 1).
struct ChunkHeaderV1 {
  magic:uint16;
  ver:uint16;
  op:uint8;
  flags:uint8;
  buffer_id:uint16;
  reserved:uint16;
  metadata_size:uint16;
  remote_id:uint32;
  local_id:uint32;
  count_or_size:uint32;
  uuid:uint64;
  padding:uint64;
  padding1:uint64;
  padding2:uint64;
  padding3:uint64;
}

// Latest header layout corresponding to the latest version (ver = 2).
struct ChunkHeader {
  // Two fixed fields. Do not change.
  magic:uint16;
  ver:uint16;

  // The following fields can change.
  // When they do, the `ver` field must be incremented in the new serializer.
  // LINT.IfChange
  op:uint8;
  flags:uint8;
  buffer_id:uint16;
  reserved:uint16;
  metadata_size:uint16;
  padding0:uint32;  // Explicit padding for 8-byte alignment of remote_id.
  remote_id:uint64;
  local_id:uint32;
  padding1:uint32;  // Explicit padding for 8-byte alignment of count_or_size.
  count_or_size:uint64;
  uuid:uint64;

  // Paddings to keep the header size always 64 bytes.
  padding2:uint64;
  padding3:uint64;
// LINT.ThenChange(chunk.h)
}

struct ChunkMetadata {
  // The following fields can change.
  // When they do, the `ver` field in ChunkHeader must be incremented.
  // LINT.IfChange
  layer_idx:uint32;
  dst_shard_idx:uint32;
  dst_offset_bytes:uint64;
  size_bytes:uint64;
// LINT.ThenChange(chunk.h)
}
