# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Repository rule exposing the locally installed torch wheel to Bazel.

TORCH_SOURCE names the site-packages directory that contains torch/. The
repository mirrors that torch/ tree with symlinks and exposes its headers.
"""

def _torch_local_repo_impl(rctx):
    torch_path = rctx.getenv("TORCH_SOURCE", "")
    if not torch_path:
        fail("TORCH_SOURCE must name the site-packages directory containing torch/")
    rctx.execute(["mkdir", "-p", "site-packages/torch"])
    rctx.execute(["cp", "-as", torch_path + "/torch/.", "site-packages/torch/"])
    if not rctx.path("site-packages/torch/include/torch/csrc/api/include/torch/torch.h").exists:
        fail("no torch headers under " + torch_path + "/torch/include")
    rctx.execute(["find", "site-packages", "(", "-name", "BUILD", "-o", "-name", "BUILD.bazel", ")", "-delete"])
    rctx.file("BUILD.bazel", """# Generated by torch_local_repo.
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_python//python:py_library.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "torch_headers",
    hdrs = glob(
        [
            "site-packages/torch/include/**/*.h",
            "site-packages/torch/include/**/*.hpp",
            "site-packages/torch/include/**/*.cuh",
            "site-packages/torch/include/**/*.inc",
            "site-packages/torch/include/**/*.inl",
            "site-packages/torch/include/**/*.tcc",
        ],
        allow_empty = True,
    ),
    includes = [
        "site-packages/torch/include",
        "site-packages/torch/include/torch/csrc/api/include",
        "site-packages/torch/include/kineto",
    ],
    deps = ["@com_google_protobuf//:protobuf"],
)

py_library(name = "torch")
""")

torch_local_repo = repository_rule(
    implementation = _torch_local_repo_impl,
    environ = ["TORCH_SOURCE"],
    local = True,
)
