# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Repository rule exposing the installed torch_tpu wheel's headers to Bazel.

TORCH_TPU_SOURCE names the site-packages directory that contains torch_tpu/.
The wheel ships the tensor_buffer interface header under torch_tpu/include/
(csrc/api/tensor_buffer.h) and the XLA commit it was built with in
torch_tpu/include/XLA_COMMIT.
"""

def _torch_tpu_wheel_repo_impl(rctx):
    src = rctx.getenv("TORCH_TPU_SOURCE", "")
    if not src:
        fail("TORCH_TPU_SOURCE must name the site-packages directory containing torch_tpu/")
    include = src + "/torch_tpu/include"
    if not rctx.path(include + "/csrc/api/tensor_buffer.h").exists:
        fail("no torch_tpu public headers under " + include)
    rctx.execute(["mkdir", "-p", "site-packages/torch_tpu"])
    rctx.execute(["cp", "-as", include, "site-packages/torch_tpu/include"])
    rctx.file("BUILD.bazel", """# Generated by torch_tpu_wheel_repo.
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# The shipped header refuses compilation without this define: the interface
# is provided for tpu_sync only, with no compatibility promise.
cc_library(
    name = "api_headers",
    hdrs = glob(["site-packages/torch_tpu/include/**/*.h"]),
    defines = ["TORCH_TPU_USER_UNSUPPORTED_PRIVATE_HEADERS"],
    includes = ["site-packages/torch_tpu/include"],
)
""")

torch_tpu_wheel_repo = repository_rule(
    implementation = _torch_tpu_wheel_repo_impl,
    environ = ["TORCH_TPU_SOURCE"],
    local = True,
)
