name: Record H2D/D2H Baselines

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  record:
    uses: google-ml-infra/bap/.github/workflows/run-benchmarks.yaml@82682aceae058a272d67c5e8bb4e8eba2da7b7c2 # main
    with:
      registry_file: "tpu_sync/benchmarks/benchmark_registry_record.pbtxt"
      bap_ref: "82682aceae058a272d67c5e8bb4e8eba2da7b7c2"
      runner: "linux-x86-n2-32"
